services:
- type: web
  name: Hazard_tool
  env: python
  region: singapore
  plan: free

  buildCommand: |
    apt-get update && apt-get install -y \
    gdal-bin libgdal-dev libgeos-dev libproj-dev
    pip install --upgrade pip
    pip install -r requirements.txt

  startCommand: gunicorn app:app
